### ISSUE TITLE
Rename CLI script

### ISSUE THREAD

**Issue by kba** [OCR-D/quiver-back-end#24]
`ocrd-kwalitee` is not ideal because for resource discovery we inspect `$PATH` for all scripts that match `^ocrd-` under the assumption that these are OCR-D processors. `ocrd-kwalitee` (like `ocrd-import`) is not an OCR-D processor but looks like one. It's not that this causes problems as such, they are excluded from resource lookup but it slightly impacts performance of the resource discovery and is a source of confusion

Possible replacements include `kwalitee-ocrd` or `ocrd_kwalitee` or something else if anybody has a better name, not starting with `ocrd-`.

**Comment by mweidling** [comment]
Closed by https://github.com/OCR-D/quiver-back-end/pull/31.
